/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeleteTableFrame.java
 *
 * Created on Feb 22, 2012, 12:37:05 PM
 */
package sqlsuite;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Administrator
 */
public class DeleteTableFrame extends javax.swing.JFrame {
    private Component list;

    /** Creates new form DeleteTableFrame */
    public DeleteTableFrame() {
        initComponents();
        setLocationRelativeTo(null);
        insertIntoList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton_Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 286));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(82, 25, 217, 115);

        jLabel1.setText("Table Names:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 25, 68, 28);

        jButton_Delete.setText("Delete Table(s)");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Delete);
        jButton_Delete.setBounds(235, 172, 141, 39);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 440, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    dispose();
    new MenuWindowFrame().setVisible(true);
}//GEN-LAST:event_formWindowClosing

private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
// TODO add your handling code here:
    int confirm=JOptionPane.showConfirmDialog(null,"Are you sure you want to Delete?","Message",JOptionPane.YES_NO_OPTION);
    if(confirm==0)
    {
        DefaultListModel dlm=new DefaultListModel();
        int count3[]=jList1.getSelectedIndices();
        Object selectedValues[] =jList1.getSelectedValues();
        for(int i=0;i<count3.length;i++)
        {
            String str3="drop table "+selectedValues[i]+";";
            EstablishConnection.connec(str3);
        }
        for(int i=0;i<count3.length;i++)
        {
                dlm.removeElementAt(count3[i]);
        }
        dispose();
        new MenuWindowFrame().setVisible(true);
    }
}//GEN-LAST:event_jButton_DeleteActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DeleteTableFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void insertIntoList() {
        try {
            ResultSet resultSet=EstablishConnection.executeQuery("select * from tab");
            DefaultListModel dlm=new DefaultListModel();
                while(resultSet.next())
                {
                    String value=resultSet.getString("TNAME");
                    System.out.println("TName:"+value);
                    dlm.addElement(value);
                    //jList1.addItem((Object)value);
                }
                resultSet.close();
                jList1.setModel(dlm);
                JScrollPane jsp = new JScrollPane(list);                
        } catch (SQLException ex) {
            Logger.getLogger(DeleteTableFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
