/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * DeletetablePanel.java
 *
 * Created on Mar 8, 2012, 5:42:42 PM
 */
package sqlsuite;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
/**
 *
 * @author Administrator
 */
public class DeletetablePanel extends javax.swing.JPanel {
private Component list;
    /** Creates new form DeletetablePanel */
    public DeletetablePanel() {
        initComponents();
        insertIntoList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton_Delete = new javax.swing.JButton();
        jB_closeTab = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setLayout(null);

        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(390, 220, 260, 150);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Table Names:");
        add(jLabel1);
        jLabel1.setBounds(260, 220, 110, 28);

        jButton_Delete.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_Delete.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Delete.setText("Delete Table(s)");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        add(jButton_Delete);
        jButton_Delete.setBounds(420, 400, 180, 39);

        jB_closeTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/cross.jpg"))); // NOI18N
        jB_closeTab.setToolTipText("Close Tab");
        jB_closeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_closeTabActionPerformed(evt);
            }
        });
        add(jB_closeTab);
        jB_closeTab.setBounds(870, 60, 30, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("SQL SUITE FOR ORACLE");
        add(jLabel3);
        jLabel3.setBounds(330, 80, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 670);
    }// </editor-fold>//GEN-END:initComponents

private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
// TODO add your handling code here:
    int confirm=JOptionPane.showConfirmDialog(null,"Are you sure you want to Delete?","Message",JOptionPane.YES_NO_OPTION);
    if(confirm==0)
    {
        DefaultListModel dlm=new DefaultListModel();
        int count3[]=jList1.getSelectedIndices();
        Object selectedValues[] =jList1.getSelectedValues();
        String str3="";
        for(int i=0;i<count3.length;i++)
        {
            str3="drop table "+selectedValues[i]+";";
            EstablishConnection.connec(str3);
        }
        JOptionPane.showMessageDialog(null,"QUERY:"+str3,"Query Information",JOptionPane.INFORMATION_MESSAGE);
//        for(int i=0;i<count3.length;i++)
//        {
//                dlm.removeElementAt(count3[i]);
//        }
        //dispose();
        //new MenuWindowFrame().setVisible(true);
        MainWindowClass.jTabbedPane_view.remove(MainWindowClass.tabdel);
        MainWindowClass.jTabbedPane_view.add(new DeletetablePanel(),MainWindowClass.tabdel);
        MainWindowClass.jTabbedPane_view.setTitleAt(MainWindowClass.tabdel,"Delete Tables");
        MainWindowClass.jTabbedPane_view.setSelectedIndex(MainWindowClass.tabdel);
    }
}//GEN-LAST:event_jButton_DeleteActionPerformed

private void jB_closeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_closeTabActionPerformed
int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to close this tab?","Message",JOptionPane.YES_NO_OPTION);
//int confirm=JOptionPane.showConfirmDialog(null, "Error is here", "Error", YES, WIDTH)       
if(confirm==0)
         {
                MainWindowClass.jTabbedPane_view.remove(MainWindowClass.tabdel);
                MainWindowClass.del="close";
                //MainWindowClass.jTabbedPane_view.
                MyUtilities.closeTab(MainWindowClass.tabdel);
         }
}//GEN-LAST:event_jB_closeTabActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_closeTab;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void insertIntoList() {
        try {
            ResultSet resultSet=EstablishConnection.executeQuery("select * from tab");
            DefaultListModel dlm=new DefaultListModel();
                while(resultSet.next())
                {
                    String value=resultSet.getString("TNAME");
                    System.out.println("TName:"+value);
                    dlm.addElement(value);
                    //jList1.addItem((Object)value);
                }
                resultSet.close();
                jList1.setModel(dlm);
                JScrollPane jsp = new JScrollPane(list);                
        } catch (SQLException ex) {
            Logger.getLogger(DeleteTableFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}