/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DuplicationOfTableFrame.java
 *
 * Created on Dec 5, 2011, 12:35:57 AM
 */
package sqlsuite;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Narendher
 */
public class DuplicationOfTableFrame extends javax.swing.JFrame {
    public JScrollPane jsp;
    public Connection conn;
    public Statement statement;
    public ResultSetMetaData rsmd;
    public String selectname;
    DefaultTableModel dtm=null;
    /** Creates new form DuplicationOfTableFrame */
    public DuplicationOfTableFrame() throws SQLException {
         initComponents();
         setLocationRelativeTo(null);
         resultSetRetieve();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cb_DuplicateTableSelection = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dup_Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Duplication of a Table");
        setMinimumSize(new java.awt.Dimension(700, 580));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                WindowClosingDuplicateTableFrame(evt);
            }
        });
        getContentPane().setLayout(null);

        Cb_DuplicateTableSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cb_DuplicateTableSelectionItemStateChanged(evt);
            }
        });
        Cb_DuplicateTableSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_DuplicateTableSelectionActionPerformed(evt);
            }
        });
        getContentPane().add(Cb_DuplicateTableSelection);
        Cb_DuplicateTableSelection.setBounds(308, 172, 142, 20);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("New Table Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(149, 136, 130, 17);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Existing Table Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(149, 174, 160, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(308, 134, 136, 20);

        Dup_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Column Name", "Data Type", "Width", "Precision", "Constraint"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        Dup_Table.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(Dup_Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(72, 210, 583, 215);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Create Table");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 460, 139, 52);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setText("Note: Please Select the rows using ctrl key to create a duplicate table.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(92, 436, 390, 22);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 36));
        jLabel4.setText("SQL SUITE FOR ORACLE");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 51, 51)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(116, 34, 486, 57);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 690, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rowSelected[]=Dup_Table.getSelectedRows();
        if(rowSelected.length==0)
	{
		JOptionPane.showMessageDialog(null,"No Row Selected");
		return;
	}
        else
        {
        String qry="create table "+jTextField1.getText()+" as select ";
        for(int i=0;i<rowSelected.length;i++)
        {
                qry+=""+Dup_Table.getValueAt(rowSelected[i],0)+",";
        }
        qry=qry.substring(0,qry.length()-1);
        qry+=" from "+Cb_DuplicateTableSelection.getSelectedItem();
        try
        {
                int confirm=statement.executeUpdate(qry);
                if(confirm ==0)
                        JOptionPane.showMessageDialog(null,"Table Not Created");
                else
                        JOptionPane.showMessageDialog(null,"Table Created");
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null,"ERROR :"+e);
                return;
        }
        JOptionPane.showMessageDialog(null, " Query:" +qry);
        dispose();
        new MenuWindowFrame().setVisible(true);
        }
    }

    private void retriveDescriptionOfGivenTable(String name) {
        try {
            String qry = "select * from "+name;
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection conn=DriverManager.getConnection("jdbc:odbc:MyPrjDSN",StaticData.userid,StaticData.password);
            Statement stmt=conn.createStatement();
            ResultSet resultset = stmt.executeQuery(qry);
            rsmd = resultset.getMetaData();
            int columnCount = rsmd.getColumnCount();
            //Dup_Table.addRowSelectionInterval(0,columnCount);
            for (int i = 0; i < columnCount; i++) {
                Dup_Table.setValueAt(rsmd.getColumnName(i + 1), i, 0);
                Dup_Table.setValueAt(rsmd.getColumnTypeName(i + 1), i, 1);
                if ((""+rsmd.getColumnTypeName(i + 1)).equals("number")) {
                    Dup_Table.setValueAt(""+(rsmd.getColumnDisplaySize(i + 1) - 2), i, 2);
                } else {
                    Dup_Table.setValueAt(""+rsmd.getColumnDisplaySize(i + 1), i, 2);
                }
                Dup_Table.setValueAt(""+rsmd.getScale(i + 1), i, 3);
                if ((""+rsmd.isNullable(i + 1)).equals("1")) {
                    Dup_Table.setValueAt("NULL", i, 4);
                } else {
                    Dup_Table.setValueAt("NOT NULL", i, 4);
                }
            }
        } catch (Exception ex) {
                        System.out.println("Exception in retriveDescriptionOfGivenTable:"+ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private void Cb_DuplicateTableSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_DuplicateTableSelectionActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_Cb_DuplicateTableSelectionActionPerformed

private void WindowClosingDuplicateTableFrame(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowClosingDuplicateTableFrame
    // TODO add your handling code here:
 int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to QUIT?","Message",JOptionPane.YES_NO_OPTION);
 if(confirm==0)
    {
        new MenuWindowFrame().setVisible(true);
        dispose();
 return;
 }
 else
     return;
}//GEN-LAST:event_WindowClosingDuplicateTableFrame
private void Cb_DuplicateTableSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cb_DuplicateTableSelectionItemStateChanged
    int n=jScrollPane1.getComponentCount();
        for(int i=0;i<n;i++)
            for(int j=0;j<5;j++)
            ((DefaultTableModel)Dup_Table.getModel()).setValueAt("", i, j);
            //((DefaultTableModel)Dup_Table.getModel()).removeRow(i);
    String name=(String)evt.getItem();
    retriveDescriptionOfGivenTable(name);
}//GEN-LAST:event_Cb_DuplicateTableSelectionItemStateChanged
 /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DuplicationOfTableFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DuplicationOfTableFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Cb_DuplicateTableSelection;
    private javax.swing.JTable Dup_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
   private void resultSetRetieve() throws SQLException {
        try {
            //((DefaultTableModel)Dup_Table.getModel()).setRowCount(1000);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection("jdbc:odbc:MyPrjDSN",StaticData.userid,StaticData.password);
            statement = conn.createStatement();
            ResultSet rs = statement.executeQuery("select * from tab");
            while(rs.next())
            {
                String value=rs.getString("TNAME");
                System.out.println("TName:"+value);
                Cb_DuplicateTableSelection.addItem((Object)value);
            }
           rs.close();
        } catch (Exception ex) {
            System.out.println("Exception in Duplication of Table:"+ex);
        }
        String name=(String)Cb_DuplicateTableSelection.getSelectedItem();
        retriveDescriptionOfGivenTable(name);
    }
}
