 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * LoginFrame.java
 *
 * Created on Oct 25, 2011, 6:58:48 PM
 */
package sqlsuite;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author narendher
 */
public class LoginFrame extends javax.swing.JFrame {
    private Connection conn;
    private Statement st;
    private ResultSet rs;
    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton_login = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 24));
        jLabel3.setText("SQL SUITE FOR ORACLE");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 0, 102), null, new java.awt.Color(255, 102, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQLSUITE");
        setBackground(new java.awt.Color(102, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(535, 382));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14));
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("USERNAME:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 160, 80, 31);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14));
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 210, 90, 27);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 2, 12));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 160, 170, 29);

        jButton_login.setBackground(new java.awt.Color(204, 204, 204));
        jButton_login.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        jButton_login.setForeground(new java.awt.Color(102, 0, 0));
        jButton_login.setText("LOGIN");
        jButton_login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login);
        jButton_login.setBounds(230, 300, 90, 41);

        jPasswordField1.setFont(new java.awt.Font("Comic Sans MS", 2, 12));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(250, 210, 170, 29);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 24));
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("SQL SUITE FOR ORACLE");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 70, 280, 35);

        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/fxfx_abstract_backgrounds_dolphin.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 560, 362);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed
/** Verify the given username and password */
private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            DriverManager.getConnection("jdbc:odbc:MyPrjDSN",jTextField1.getText(),jPasswordField1.getText());
            //st = conn.createStatement();             
            StaticData.userid=jTextField1.getText();
            StaticData.password=jPasswordField1.getText();
            dispose();
            //JFrame MenuWindowClass=new MainWindowClass();
             new MainWindowClass().setVisible(true);
           //new MenuWindowFrame().setVisible(true);        
}//GEN-LAST:event_jButton_loginActionPerformed
        catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,"Please enter correct Login details");
        }        catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
