/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * MainWindowClass.java
 *
 * Created on Mar 1, 2012, 11:45:13 AM
 */
package sqlsuite;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 */
public class MainWindowClass extends javax.swing.JFrame {
    JTabbedPane pane = new JTabbedPane();
     public static  String ct="close";
     public static  String dup="close";
     public static  String desc="close";
     public static  String cu="close";
     public static  String ins="close";
     public static  String mod="close";
     public static  String del="close";
     public static  String cv="close";
     public static  String cr="close";
     public static  String pr="close";
     public static  int tabct=-1,tabdup=-1,tabdesc=-1,tabcu=-1,tabins=-1,tabmod=-1,tabdel=-1,tabcv=-1,tabcr=-1,tabpr=-1;
    /** Creates new form MainWindowClass */
    public MainWindowClass() {
        initComponents();
        setLocationRelativeTo(null);
//        jTabbedPane1.
        if(!StaticData.userid.equals("project"))
        {
            jButton_createUser.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton_createTable = new javax.swing.JButton();
        jButton_Duplication = new javax.swing.JButton();
        jButton_Description = new javax.swing.JButton();
        jButton_createUser = new javax.swing.JButton();
        jButton_Insert = new javax.swing.JButton();
        jButton_modify = new javax.swing.JButton();
        jButton_DeleteTable = new javax.swing.JButton();
        jButton_CreateView = new javax.swing.JButton();
        jButton_LogOut = new javax.swing.JButton();
        jButton_Condition = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane_view = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SQLSuite For Oracle");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jButton_createTable.setText("Create Table");
        jButton_createTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createTableActionPerformed(evt);
            }
        });

        jButton_Duplication.setText("Duplication Of Table");
        jButton_Duplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DuplicationActionPerformed(evt);
            }
        });

        jButton_Description.setText("Description Of Table");
        jButton_Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DescriptionActionPerformed(evt);
            }
        });

        jButton_createUser.setText("Create User");
        jButton_createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createUserActionPerformed(evt);
            }
        });

        jButton_Insert.setText("Insert/Retrieve");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_modify.setText("Modify Table Contents");
        jButton_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifyActionPerformed(evt);
            }
        });

        jButton_DeleteTable.setText("Delete Table/view");
        jButton_DeleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteTableActionPerformed(evt);
            }
        });

        jButton_CreateView.setText("Create View");
        jButton_CreateView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateViewActionPerformed(evt);
            }
        });

        jButton_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/gnome_panel_force_quit.png"))); // NOI18N
        jButton_LogOut.setToolTipText("LOG OUT");
        jButton_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogOutActionPerformed(evt);
            }
        });

        jButton_Condition.setText("Conditional Retrive");
        jButton_Condition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConditionActionPerformed(evt);
            }
        });

        jButton1.setText("Practice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_createUser, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Condition, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_CreateView, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_DeleteTable, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Insert, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Description, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Duplication, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_createTable, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton_createTable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Duplication, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_DeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_CreateView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Condition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_createUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane_view.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane_view.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane_view, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_view, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton_createTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createTableActionPerformed
        
    if(ct.equals("close"))
        {
            tabct=jTabbedPane_view.getTabCount();
            jTabbedPane_view.add("Table Creation",new TableCreationPanel()); 
            //jTabbedPane_view.setComponentAt(1,new ButtonTabComponent(jTabbedPane_view));
            ct="open";
            jTabbedPane_view.setSelectedIndex(tabct);
            
        }
        else
        {
            jTabbedPane_view.setSelectedIndex(tabct);
        }
}//GEN-LAST:event_jButton_createTableActionPerformed
    private void jButton_DuplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DuplicationActionPerformed
        if(dup.equals("close"))
        {
            tabdup=jTabbedPane_view.getTabCount();
            jTabbedPane_view.addTab("Duplication",new DuplicationPanel());
            dup="open";
            jTabbedPane_view.setSelectedIndex(tabdup);
        }
        else
        {
            jTabbedPane_view.setSelectedIndex(tabdup);
        }            
        //initComponents();
    }//GEN-LAST:event_jButton_DuplicationActionPerformed
 
private void jButton_DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DescriptionActionPerformed
    if(desc.equals("close"))
    {
        tabdesc=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("Description",new DescriptionPanel());
        desc="open";
        jTabbedPane_view.setSelectedIndex(tabdesc);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabdesc);
    }
        //initComponents();
}//GEN-LAST:event_jButton_DescriptionActionPerformed

private void jButton_createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createUserActionPerformed
    if(cu.equals("close"))    
    {
        tabcu=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("UserCreation",new UserCreationPanel());
        cu="open";
        jTabbedPane_view.setSelectedIndex(tabcu);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabcu);
    }
}//GEN-LAST:event_jButton_createUserActionPerformed

private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
    if(ins.equals("close"))
    {
        tabins=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("Insert",new SelectTablePanel_insert());
        ins="open";
        jTabbedPane_view.setSelectedIndex(tabins);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabins);
    }
}//GEN-LAST:event_jButton_InsertActionPerformed

private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed
    if(mod.equals("close"))
    {
        tabmod=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("Modify",new SelectTablePanel_Modify());
        mod="open";
        jTabbedPane_view.setSelectedIndex(tabmod);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabmod);
    }
}//GEN-LAST:event_jButton_modifyActionPerformed

private void jButton_DeleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteTableActionPerformed
    if(del.contains("close"))
    {
        tabdel=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("Delete",new DeletetablePanel());
        del="open";
        jTabbedPane_view.setSelectedIndex(tabdel);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabdel);
    }
}//GEN-LAST:event_jButton_DeleteTableActionPerformed
private void jButton_CreateViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateViewActionPerformed
    if(cv.equals("close"))
    {
        tabcv=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("View Creation",new SelectTablePanel_CreateView());
        cv="open";
        jTabbedPane_view.setSelectedIndex(tabcv);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabcv);
    }
}//GEN-LAST:event_jButton_CreateViewActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to QUIT?","Message",JOptionPane.YES_NO_OPTION);
    if(confirm==0)
    {
        jTabbedPane_view.removeAll();
        dispose();
        new LoginFrame().setVisible(true);
    }
    else
    {
        return;
    }
}//GEN-LAST:event_formWindowClosing

private void jButton_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogOutActionPerformed
    int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to QUIT?","Message",JOptionPane.YES_NO_OPTION);
    if(confirm==0)
    {
        dispose();
        new LoginFrame().setVisible(true);
    }
    else
    {
        return;
    }
}//GEN-LAST:event_jButton_LogOutActionPerformed

private void jButton_ConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConditionActionPerformed
// TODO add your handling code here:
    StaticData.choice=1;
    if(cr.equals("close"))
    {
        tabcr=jTabbedPane_view.getTabCount();
        jTabbedPane_view.add("Conditional Retreival",new SelectTablePanel_ConditionalRetrieve());
        cr="open";
        jTabbedPane_view.setSelectedIndex(tabcr);
    }
    else
    {
        jTabbedPane_view.setSelectedIndex(tabcr);
    }
}//GEN-LAST:event_jButton_ConditionActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(pr.equals("close"))
        {
            tabpr=jTabbedPane_view.getTabCount();
            jTabbedPane_view.add("Practicing",new PractisingPanel()); 
            //jTabbedPane_view.setComponentAt(1,new() ButtonTabComponent(jTabbedPane_view));
            pr="open";
            jTabbedPane_view.setSelectedIndex(tabpr);
            
        }
        else
        {
            jTabbedPane_view.setSelectedIndex(tabpr);
        }
}//GEN-LAST:event_jButton1ActionPerformed
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindowClass().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Condition;
    private javax.swing.JButton jButton_CreateView;
    private javax.swing.JButton jButton_DeleteTable;
    private javax.swing.JButton jButton_Description;
    private javax.swing.JButton jButton_Duplication;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_LogOut;
    private javax.swing.JButton jButton_createTable;
    private javax.swing.JButton jButton_createUser;
    private javax.swing.JButton jButton_modify;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTabbedPane jTabbedPane_view;
    // End of variables declaration//GEN-END:variables
}
