
package sqlsuite;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuWindowFrame.java
 *
 * Created on Dec 5, 2011, 12:50:33 PM
 */
/**
 *
 * @author narendher
 */
public class MenuWindowFrame extends javax.swing.JFrame {
    /** Creates new form MenuWindowFrame */
    public MenuWindowFrame() {
        initComponents();
        StaticData.choice=0;
        if(!"project".equals(StaticData.userid))
        {
            jButton_createuser.setVisible(false);
        }
        /** MAkes the Frame to be located at the center all the time */
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_description = new javax.swing.JButton();
        jButton_createtable = new javax.swing.JButton();
        jButton_Duplicate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_createuser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton_createAView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User's Menu");
        setMinimumSize(new java.awt.Dimension(565, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton_description.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_description.setForeground(new java.awt.Color(0, 0, 204));
        jButton_description.setText("Description of Table");
        jButton_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_description);
        jButton_description.setBounds(87, 240, 180, 41);

        jButton_createtable.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_createtable.setForeground(new java.awt.Color(51, 0, 204));
        jButton_createtable.setText("Create Table");
        jButton_createtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createtableActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_createtable);
        jButton_createtable.setBounds(87, 172, 172, 41);

        jButton_Duplicate.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_Duplicate.setForeground(new java.awt.Color(0, 0, 204));
        jButton_Duplicate.setText("Duplication");
        jButton_Duplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DuplicateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Duplicate);
        jButton_Duplicate.setBounds(87, 300, 172, 42);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("MENU FRAME OPTIONS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(203, 121, 218, 33);

        jButton_createuser.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_createuser.setForeground(new java.awt.Color(0, 0, 204));
        jButton_createuser.setText("CreateUser");
        jButton_createuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createuserActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_createuser);
        jButton_createuser.setBounds(87, 360, 172, 45);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Insert/Retrieve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(315, 173, 165, 41);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(315, 241, 165, 41);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Delete Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(315, 303, 165, 39);

        jButton_createAView.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_createAView.setForeground(new java.awt.Color(0, 0, 204));
        jButton_createAView.setText("Create A View");
        jButton_createAView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createAViewActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_createAView);
        jButton_createAView.setBounds(315, 361, 165, 44);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24));
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("SQL SUITE FOR ORACLE");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(0, 0, 0), null, new java.awt.Color(255, 102, 51)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(144, 40, 311, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(51, 0, 204)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 540, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/** Initializes the TableCreation Frame and disposes the present MenuWindowFrame */
private void jButton_createtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createtableActionPerformed
        // TODO add your handling code here:       
        dispose();
        new TableCreationFrame().setVisible(true);
}//GEN-LAST:event_jButton_createtableActionPerformed
/** Initializes the DescriptionOfTableFrame and disposes the present MenuWindowFrame */
private void jButton_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_descriptionActionPerformed
        try 
        {
            dispose();
            JFrame DescriptionOfTableFrame = new DescriptionOfTableFrame();
            DescriptionOfTableFrame.setVisible(true);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(MenuWindowFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton_descriptionActionPerformed
/** Initializes the DuplicationOfTableFrame and disposes the present MenuWindowFrame */
private void jButton_DuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DuplicateActionPerformed
        try {
            dispose();
            JFrame Duplicate = new DuplicationOfTableFrame();
            Duplicate.setVisible(true);            
        } catch (SQLException ex) {
            Logger.getLogger(MenuWindowFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton_DuplicateActionPerformed
/** Initializes the USerCReation Frame and disposes the present MenuWindowFrame */
private void jButton_createuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createuserActionPerformed
    // TODO add your handling code here:
    dispose();
    JFrame UserCreation=new UserCreationFrame();
    UserCreation.setVisible(true);
}//GEN-LAST:event_jButton_createuserActionPerformed
/** Display the message and confirms whether the user really wants to quit */
private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
    int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to QUIT?","Message",JOptionPane.YES_NO_OPTION);
    if(confirm==0)
    {
        new LoginFrame().setVisible(true);
        dispose();
        return;
    }
    else
        return;
}//GEN-LAST:event_formWindowClosing

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 // TODO add your handling code here:
    dispose();
    new SelectTableFrame().setVisible(true);
//    JFrame SelectTableFrame=new SelectTableFrame();
//    SelectTableFrame.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StaticData.choice=2;
        dispose();
        new SelectTableFrame().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        dispose();
        new DeleteTableFrame().setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_createAViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createAViewActionPerformed
        // TODO add your handling code here:
        StaticData.choice=3;
        dispose();
        new SelectTableFrame().setVisible(true);
    }//GEN-LAST:event_jButton_createAViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MenuWindowFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Duplicate;
    private javax.swing.JButton jButton_createAView;
    private javax.swing.JButton jButton_createtable;
    private javax.swing.JButton jButton_createuser;
    private javax.swing.JButton jButton_description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
