/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectTablePanel.java
 *
 * Created on Mar 8, 2012, 5:21:55 PM
 */
package sqlsuite;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SelectTablePanel_Modify extends javax.swing.JPanel {

    /** Creates new form SelectTablePanel */
    public SelectTablePanel_Modify() {
        initComponents();
        resultSetRetrieve();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCB_TableList = new javax.swing.JComboBox();
        jButton_Showcontents = new javax.swing.JButton();
        jB_closeTab = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 36));
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("SQL SUITE FOR ORACLE");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), null, new java.awt.Color(0, 102, 102)));
        add(jLabel3);
        jLabel3.setBounds(310, 220, 466, 57);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("NOTE: Please slect the TABLE Name  from the below list");
        add(jLabel2);
        jLabel2.setBounds(370, 300, 310, 31);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14));
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("TableName:");
        add(jLabel1);
        jLabel1.setBounds(370, 350, 80, 24);

        jCB_TableList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCB_TableListItemStateChanged(evt);
            }
        });
        add(jCB_TableList);
        jCB_TableList.setBounds(470, 350, 207, 35);

        jButton_Showcontents.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_Showcontents.setForeground(new java.awt.Color(0, 102, 102));
        jButton_Showcontents.setText("ShowContents");
        jButton_Showcontents.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        jButton_Showcontents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowcontentsActionPerformed(evt);
            }
        });
        add(jButton_Showcontents);
        jButton_Showcontents.setBounds(470, 410, 140, 38);

        jB_closeTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/cross.jpg"))); // NOI18N
        jB_closeTab.setToolTipText("Close Tab");
        jB_closeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_closeTabActionPerformed(evt);
            }
        });
        add(jB_closeTab);
        jB_closeTab.setBounds(870, 60, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1020, 670);
    }// </editor-fold>//GEN-END:initComponents

private void jCB_TableListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCB_TableListItemStateChanged
// TODO add your handling code here:
   StaticData.tablename_mod=(String) jCB_TableList.getSelectedItem();
}//GEN-LAST:event_jCB_TableListItemStateChanged

private void jButton_ShowcontentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowcontentsActionPerformed
        MainWindowClass.jTabbedPane_view.remove(MainWindowClass.tabmod);
        MainWindowClass.jTabbedPane_view.add(new ModifyPanel(),MainWindowClass.tabmod);;
        MainWindowClass.jTabbedPane_view.setTitleAt(MainWindowClass.tabmod,"Modify");
        MainWindowClass.jTabbedPane_view.setSelectedIndex(MainWindowClass.tabmod);
}//GEN-LAST:event_jButton_ShowcontentsActionPerformed

private void jB_closeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_closeTabActionPerformed
int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to close this tab?","Message",JOptionPane.YES_NO_OPTION);
//int confirm=JOptionPane.showConfirmDialog(null, "Error is here", "Error", YES, WIDTH)       
if(confirm==0)
         {
                MainWindowClass.jTabbedPane_view.remove(MainWindowClass.tabmod);
                MainWindowClass.mod="close";
                //MainWindowClass.jTabbedPane_view.
                MyUtilities.closeTab(MainWindowClass.tabmod);
         }
}//GEN-LAST:event_jB_closeTabActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_closeTab;
    private javax.swing.JButton jButton_Showcontents;
    private javax.swing.JComboBox jCB_TableList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void resultSetRetrieve() {
        System.out.println("TName: are as follow");
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection conn=DriverManager.getConnection("jdbc:odbc:MyPrjDSN",StaticData.userid,StaticData.password);
            Statement stmt=conn.createStatement();
            ResultSet resultSet=stmt.executeQuery("select * from tab");
            while(resultSet.next())
            {
                String value=resultSet.getString("TNAME");
                System.out.println("TName:"+value);
               jCB_TableList.addItem((Object)value);
            }
            resultSet.close();
        }
        catch(Exception e)
        {
            System.out.println("Exception: "+e);
        }
       StaticData.tablename=(String) jCB_TableList.getSelectedItem();
    }
}
