/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableCreationPanel.java
 *
 * Created on Mar 7, 2012, 9:03:40 PM
 */
package sqlsuite;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class TableCreationPanel extends javax.swing.JPanel {

    /** Creates new form TableCreationPanel */
    public TableCreationPanel() {
        initComponents();
        setVisible(true);
        //jButton_Query.setVisible(false);
        //jButton_AddColumn.setToolTipText("Adds a column to the table");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_AddColumn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTF_columnName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_dataType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTF_width = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_precision = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_NULL = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton_CreateTable = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jB_closeTab = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);

        jButton_AddColumn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_AddColumn.setForeground(new java.awt.Color(0, 0, 153));
        jButton_AddColumn.setText("Add Column");
        jButton_AddColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        jButton_AddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddColumnActionPerformed(evt);
            }
        });
        add(jButton_AddColumn);
        jButton_AddColumn.setBounds(71, 503, 138, 44);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(420, 70, 163, 28);
        add(jTF_columnName);
        jTF_columnName.setBounds(115, 137, 112, 21);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Enter TableName:");
        add(jLabel1);
        jLabel1.setBounds(270, 80, 130, 16);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("ColumnName:");
        add(jLabel2);
        jLabel2.setBounds(10, 136, 95, 19);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("DataType:");
        add(jLabel3);
        jLabel3.setBounds(245, 136, 80, 19);

        jComboBox_dataType.setFont(new java.awt.Font("Verdana", 1, 12));
        jComboBox_dataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "varchar", "number" }));
        jComboBox_dataType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_dataTypeItemStateChanged(evt);
            }
        });
        jComboBox_dataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_dataTypeActionPerformed(evt);
            }
        });
        add(jComboBox_dataType);
        jComboBox_dataType.setBounds(335, 136, 90, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Width:");
        add(jLabel4);
        jLabel4.setBounds(435, 136, 50, 19);

        jTF_width.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_widthActionPerformed(evt);
            }
        });
        add(jTF_width);
        jTF_width.setBounds(495, 137, 95, 21);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Precision:");
        add(jLabel6);
        jLabel6.setBounds(608, 136, 70, 19);

        jTF_precision.setText("0");
        add(jTF_precision);
        jTF_precision.setBounds(696, 137, 70, 20);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Null:");
        add(jLabel5);
        jLabel5.setBounds(776, 138, 40, 14);

        jComboBox_NULL.setFont(new java.awt.Font("Verdana", 1, 12));
        jComboBox_NULL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOT NULL", "NULL" }));
        add(jComboBox_NULL);
        jComboBox_NULL.setBounds(820, 136, 100, 21);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jTable1.setForeground(new java.awt.Color(0, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ColumnName", "DataType", "Width", "Precision", "Constraint"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 197, 927, 287);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Delete Column");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(306, 502, 155, 46);

        jButton_CreateTable.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_CreateTable.setForeground(new java.awt.Color(0, 0, 153));
        jButton_CreateTable.setText("CREATE TABLE");
        jButton_CreateTable.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jButton_CreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateTableActionPerformed(evt);
            }
        });
        add(jButton_CreateTable);
        jButton_CreateTable.setBounds(526, 502, 175, 45);

        jButton_Clear.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_Clear.setForeground(new java.awt.Color(0, 0, 153));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        add(jButton_Clear);
        jButton_Clear.setBounds(753, 503, 150, 43);

        jB_closeTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/cross.jpg"))); // NOI18N
        jB_closeTab.setToolTipText("Close Tab");
        jB_closeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_closeTabActionPerformed(evt);
            }
        });
        add(jB_closeTab);
        jB_closeTab.setBounds(860, 40, 40, 40);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("SQL SUITE FOR ORACLE");
        add(jLabel8);
        jLabel8.setBounds(340, 14, 250, 40);

        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 660);
    }// </editor-fold>//GEN-END:initComponents

private void jButton_AddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddColumnActionPerformed
// TODO add your handling code here:
if(jTextField1.getText().equals(""))
{
     JOptionPane.showMessageDialog(null,"No empty Values are Allowed in the table name field","ERROR",JOptionPane.WARNING_MESSAGE);
}
else
{
    if((jTF_columnName.getText().equals("")||(jTF_width.getText().equals("")||(jTF_precision.getText().equals("")))))
    {
                JOptionPane.showMessageDialog(null," No Empty Values Are Allowed"+"\n Enter the TableName ColumnName Width and precision Values","ERROR",JOptionPane.WARNING_MESSAGE);
                jTextField1.setText("");
    }
//String ab=jTF_width.getText();
//if(jTF_width.getText().
//    JOptionPane.showMessageDialog(null,"dxgvfdb");
    else
    {   
        String str3=jTextField1.getText();        
        String pattern = "[a-zA-Z]*";
        String st2=str3.charAt(0)+"ashdd";
        Boolean fr=st2.matches(pattern);
        //System.out.println(a);
        //System.out.println(fr);
        if(fr==false)
        {
            JOptionPane.showMessageDialog(null, "A table name cannot start with _,$ pr #","ERROR",JOptionPane.WARNING_MESSAGE);
            //jTextField1.setText("");
            jTextField1.requestFocus();
        }
        else
        {
            int res1=MyUtilities.isTable_Column_Name(str3);
            if(res1==0)
            {
                JOptionPane.showMessageDialog(null, "Tablename should contain only Alpha numerics and _,$ and #","ERROR",JOptionPane.WARNING_MESSAGE);
                //jTextField1.setText("");
                jTextField1.requestFocus();
            }
            else
            {
                String str2=jTF_columnName.getText();
                if(str2.charAt(0)=='_'||str2.charAt(0)=='$'||str2.charAt(0)=='#')
                {
                    JOptionPane.showMessageDialog(null,"A Table or column name cannot start with _,$ or #","ERROR",JOptionPane.WARNING_MESSAGE);
                    jTF_columnName.requestFocus();
                }
                else
                {
                    int res=MyUtilities.isTable_Column_Name(str2);       
                    if(res==0)
                    {
                        JOptionPane.showMessageDialog(null,"Column name should contain only alpha numerics and _,$ and #","ERROR",JOptionPane.WARNING_MESSAGE);
                        //jTF_columnName.setText("");
                        jTF_columnName.requestFocus();
                    }
                    else
                    {
                        if(!MyUtilities.isNumber(jTF_width.getText()))
                        {
                            JOptionPane.showMessageDialog(null,"Please enter Only Integer Values in the width Field","ERROR",JOptionPane.WARNING_MESSAGE);
                            //jTF_width.setText("");
                            jTF_width.requestFocus();
                            //return;
                        }
                        else
                        {
                            String str[]=new String[5];
                            str[0]=jTF_columnName.getText();
                            str[1]=(String)jComboBox_dataType.getSelectedItem();
                            str[2]=jTF_width.getText();
                            str[3]=jTF_precision.getText();
                            str[4]=(String)jComboBox_NULL.getSelectedItem();
                            ((DefaultTableModel)jTable1.getModel()).addRow((Object[])str);
                            jTF_columnName.setText("");
                            jTF_width.setText("");
                            jTF_precision.setText("0");
                            jTF_columnName.requestFocus();
                        }
                    }
                } 
            }
        }            
//    String str[]=new String[5];
//    str[0]=jTF_columnName.getText();
//    str[1]=(String)jComboBox_dataType.getSelectedItem();
//    str[2]=jTF_width.getText();
//    str[3]=jTF_precision.getText();
//    str[4]=(String)jComboBox_NULL.getSelectedItem();
//    ((DefaultTableModel)jTable1.getModel()).addRow((Object[])str);
    }
}
//jTF_columnName.setText("");
//jTF_width.setText("");
//jTF_precision.setText("0");
}//GEN-LAST:event_jButton_AddColumnActionPerformed

private void jComboBox_dataTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_dataTypeItemStateChanged
        // TODO add your handling code here:
        if(jComboBox_dataType.getSelectedItem()=="varchar")
        {
            jTF_precision.setEnabled(false);
        }
        else
        {
            jTF_precision.setEnabled(true);
        }
}//GEN-LAST:event_jComboBox_dataTypeItemStateChanged

private void jComboBox_dataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_dataTypeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox_dataTypeActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jTF_widthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_widthActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTF_widthActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    int rowSelected[]=jTable1.getSelectedRows();
    if(rowSelected.length==0)
    {
        JOptionPane.showMessageDialog(null,"Please select atleast a single row to delete","ERROR",JOptionPane.WARNING_MESSAGE);
    }
    else
    {
        int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to delete the column?","Message",JOptionPane.YES_NO_OPTION);
        if(confirm==0)
         {
            
        
            for(int i=0;i<rowSelected.length;i++)
               {
                   ((DefaultTableModel)jTable1.getModel()).removeRow(rowSelected[i]);
               }
         } 
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton_CreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateTableActionPerformed
    if(jTable1.getRowCount()==0)
    {
        JOptionPane.showMessageDialog(null,"Please Enter Atleast a single row to create a Table:","ERROR",JOptionPane.WARNING_MESSAGE);
        return;
    }
    try {
            // TODO add your handling code here:
            int rows=jTable1.getRowCount();
            try {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableCreationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }              
               String st="create table "+jTextField1.getText()+"(";
               for(int i=0;i<rows;i++)
               {
                   st+=(String)jTable1.getValueAt(i, 0);
                   st+=" "+(String)jTable1.getValueAt(i, 1);
                   st+="("+(String)jTable1.getValueAt(i, 2);
                   if(((String)jTable1.getValueAt(i,1)).equals("varchar"))
                   {
                       st+=")";
                   }
                    else
                   {
                       st+=","+(String)jTable1.getValueAt(i,3)+")";
                   }
                   st+=" "+(String)jTable1.getValueAt(i,4);
                   st+=",";
               }
                st=st.substring(0,st.length()-1);
                st+=");";
                System.out.println(st);
                Connection conn=DriverManager.getConnection("jdbc:odbc:MyPrjDSN",StaticData.userid,StaticData.password);
               Statement s=conn.createStatement();
                int x=s.executeUpdate(st);
                if(x==0)
                    JOptionPane.showMessageDialog(null,"Table Not Created","Error",JOptionPane.ERROR_MESSAGE);
                else
                {
                    JOptionPane.showMessageDialog(null,"Table Created, \n QUERY:"+st,"Message",JOptionPane.INFORMATION_MESSAGE);
                    //jButton_Query.setVisible(true);
                }
                conn.close();
                s.close();
        } catch (SQLException ex) {
            System.out.println("Error"+ex);
            JOptionPane.showMessageDialog(null,"ERROR:"+ex,"ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TableCreationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  //  dispose();
   // new MenuWindowFrame().setVisible(true);
    MainWindowClass.jTabbedPane_view.remove(MainWindowClass.tabct);
    MainWindowClass.jTabbedPane_view.add(new TableCreationPanel(),MainWindowClass.tabct);
    MainWindowClass.jTabbedPane_view.setTitleAt(MainWindowClass.tabct,"Tabel Creation");
    MainWindowClass.jTabbedPane_view.setSelectedIndex(MainWindowClass.tabct);
}//GEN-LAST:event_jButton_CreateTableActionPerformed

private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
// TODO add your handling code here:
jTF_columnName.setText(null);
jTF_width.setText(null);
jComboBox_dataType.setSelectedIndex(0);
jComboBox_NULL.setSelectedIndex(0);
}//GEN-LAST:event_jButton_ClearActionPerformed

private void jB_closeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_closeTabActionPerformed
int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to close this tab?","QUIT",JOptionPane.YES_NO_OPTION);
//int confirm=JOptionPane.showConfirmDialog(null, "Error is here", "Error", YES, WIDTH)       
if(confirm==0)
         {
                MainWindowClass.jTabbedPane_view.remove(MainWindowClass.tabct);
                MainWindowClass.ct="close";
                //MainWindowClass.jTabbedPane_view.
                MyUtilities.closeTab(MainWindowClass.tabct);
         }
}//GEN-LAST:event_jB_closeTabActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_closeTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_AddColumn;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_CreateTable;
    private javax.swing.JComboBox jComboBox_NULL;
    private javax.swing.JComboBox jComboBox_dataType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_columnName;
    private javax.swing.JTextField jTF_precision;
    private javax.swing.JTextField jTF_width;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
