/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * TableCreationFrame.java
 *
 * Created on Oct 25, 2011, 8:06:28 PM
 */
package sqlsuite;
import java.lang.String;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author narendher
 */
public class TableCreationFrame extends javax.swing.JFrame {
        DefaultTableModel dtm=null;
        /** Creates new form TableCreationFrame */
        public TableCreationFrame() {
        initComponents();        
        setLocationRelativeTo(null);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_TabelName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_columnName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_dataType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTF_width = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_NULL = new javax.swing.JComboBox();
        jButton_AddColumn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_CreateTable = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jTF_precision = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Table Creation");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(941, 646));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingTC(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Enter TableName:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 120, 130, 16);
        getContentPane().add(jTF_TabelName);
        jTF_TabelName.setBounds(460, 110, 163, 28);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("ColumnName:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 180, 95, 19);
        getContentPane().add(jTF_columnName);
        jTF_columnName.setBounds(170, 180, 112, 21);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("DataType:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 180, 80, 19);

        jComboBox_dataType.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBox_dataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "varchar", "number", "date" }));
        jComboBox_dataType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_dataTypeItemStateChanged(evt);
            }
        });
        jComboBox_dataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_dataTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_dataType);
        jComboBox_dataType.setBounds(370, 180, 90, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Width:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 180, 50, 14);

        jTF_width.setText("0");
        getContentPane().add(jTF_width);
        jTF_width.setBounds(520, 180, 95, 21);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Null:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 180, 40, 14);

        jComboBox_NULL.setFont(new java.awt.Font("Verdana", 1, 12));
        jComboBox_NULL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOT NULL", "NULL" }));
        getContentPane().add(jComboBox_NULL);
        jComboBox_NULL.setBounds(820, 180, 100, 21);

        jButton_AddColumn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton_AddColumn.setForeground(new java.awt.Color(153, 0, 153));
        jButton_AddColumn.setText("Add Column");
        jButton_AddColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153)));
        jButton_AddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddColumnActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AddColumn);
        jButton_AddColumn.setBounds(80, 550, 138, 44);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jTable1.setForeground(new java.awt.Color(0, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ColumnName", "DataType", "Width", "Precision", "Constraint"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 250, 850, 287);

        jButton_CreateTable.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_CreateTable.setForeground(new java.awt.Color(153, 0, 153));
        jButton_CreateTable.setText("CREATE TABLE");
        jButton_CreateTable.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153)));
        jButton_CreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateTableActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CreateTable);
        jButton_CreateTable.setBounds(450, 550, 175, 47);

        jButton_Clear.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton_Clear.setForeground(new java.awt.Color(153, 0, 153));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153)));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Clear);
        jButton_Clear.setBounds(670, 550, 150, 43);

        jTF_precision.setText("0");
        getContentPane().add(jTF_precision);
        jTF_precision.setBounds(700, 180, 70, 20);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 15));
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Precision:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 180, 70, 19);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setText("Delete Column");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 550, 155, 46);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("SQL SUITE FOR ORACLE");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(51, 0, 255), null, new java.awt.Color(255, 51, 255)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 40, 480, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlsuite/powerpoint-curve-background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 950, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton_CreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateTableActionPerformed
    if(jTable1.getRowCount()==0)
    {
        JOptionPane.showMessageDialog(null,"Please Enter Atleast a single row to create a Table:");
        return;
    }
    try {
            // TODO add your handling code here:
            int rows=jTable1.getRowCount();
            try {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableCreationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }              
               String st="create table "+jTF_TabelName.getText()+"(";
               for(int i=0;i<rows;i++)
               {
                   st+=(String)jTable1.getValueAt(i, 0);
                   st+=" "+(String)jTable1.getValueAt(i, 1);
                   
                   if(((String)jTable1.getValueAt(i,1)).equals("varchar"))
                   {
                       st+="("+(String)jTable1.getValueAt(i, 2);
                       st+=")";
                   }
                   if(((String)jTable1.getValueAt(i, 1)).equals("date"))
                   {
                       st+="";
                   }
                   if(((String)jTable1.getValueAt(i, 1)).equals("number"))
                   {
                       st+="("+(String)jTable1.getValueAt(i, 2);
                       st+=","+(String)jTable1.getValueAt(i,3)+")";
                   }
                   st+=" "+(String)jTable1.getValueAt(i,4);
                   st+=",";
               }
                st=st.substring(0,st.length()-1);
                st+=");";
                System.out.println(st);
                Connection conn=DriverManager.getConnection("jdbc:odbc:MyPrjDSN",StaticData.userid,StaticData.password);
               Statement s=conn.createStatement();
                int x=s.executeUpdate(st);
                if(x==0)
                    JOptionPane.showMessageDialog(null,"Table Not Created");
                else
                    JOptionPane.showMessageDialog(null,"Table Created, query:"+st);           
                conn.close();
                s.close();
        } catch (SQLException ex) {
            System.out.println("Error"+ex);
            JOptionPane.showMessageDialog(null,"Error"+ex);
            Logger.getLogger(TableCreationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    dispose();
    new MenuWindowFrame().setVisible(true);
}//GEN-LAST:event_jButton_CreateTableActionPerformed
private void jButton_AddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddColumnActionPerformed
// TODO add your handling code here:
if(jTF_TabelName.getText().equals(""))
{
     JOptionPane.showMessageDialog(null,"No empty Values are Allowed in the table name field");
}
else
{
    if((jTF_columnName.getText().equals("")||(jTF_width.getText().equals("")||(jTF_precision.getText().equals("")))))
    {
        //if(jComboBox_dataType.getSelectedItem().equals(""))
                JOptionPane.showMessageDialog(null," No Empty Values Are Allowed"+"\n Enter the TableName ColumnName Width and precision Values");
                //jTextField1.setText("");
    }
//String ab=jTF_width.getText();
//if(jTF_width.getText().
//    JOptionPane.showMessageDialog(null,"dxgvfdb");
    else
    {   
        String str3=jTF_TabelName.getText();        
        String pattern = "[a-zA-Z]*";
        String st2=str3.charAt(0)+"ashdd";
        Boolean fr=st2.matches(pattern);
        //System.out.println(a);
        //System.out.println(fr);
        if(fr==false)
        {
            JOptionPane.showMessageDialog(null, "A table name cannot start with _,$ pr #");
            //jTextField1.setText("");
            jTF_TabelName.requestFocus();
        }
        else
        {
            int res1=MyUtilities.isTable_Column_Name(str3);
            if(res1==0)
            {
                JOptionPane.showMessageDialog(null, "Tablename should contain only Alpha numerics and _,$ and #");
                //jTextField1.setText("");
                jTF_TabelName.requestFocus();
            }
            else
            {
                String str2=jTF_columnName.getText();
                if(str2.charAt(0)=='_'||str2.charAt(0)=='$'||str2.charAt(0)=='#')
                {
                    JOptionPane.showMessageDialog(null,"A Table or column name cannot start with _,$ or #");
                    jTF_columnName.requestFocus();
                }
                else
                {
                    int res=MyUtilities.isTable_Column_Name(str2);       
                    if(res==0)
                    {
                        JOptionPane.showMessageDialog(null,"Column name should contain only alpha numerics and _,$ and #");
                        //jTF_columnName.setText("");
                        jTF_columnName.requestFocus();
                    }
                    else
                    {
                        if(!MyUtilities.isNumber(jTF_width.getText()))
                        {
                            JOptionPane.showMessageDialog(null,"Please enter Only Integer Values in the width Field");
                            //jTF_width.setText("");
                            jTF_width.requestFocus();
                            //return;
                        }
                        else
                        {
                            String str[]=new String[5];
                            str[0]=jTF_columnName.getText();
                            str[1]=(String)jComboBox_dataType.getSelectedItem();
                            str[2]=jTF_width.getText();
                            str[3]=jTF_precision.getText();
                            str[4]=(String)jComboBox_NULL.getSelectedItem();
                            ((DefaultTableModel)jTable1.getModel()).addRow((Object[])str);
                            jTF_columnName.setText("");
                            jTF_width.setText("0");
                            jTF_precision.setText("0");
                            jTF_columnName.requestFocus();
                            jTF_width.setEditable(true);
                            jTF_precision.setEditable(true);
                            jComboBox_dataType.setSelectedIndex(0);
                        }
                    }
                } 
            }
        }            
//    String str[]=new String[5];
//    str[0]=jTF_columnName.getText();
//    str[1]=(String)jComboBox_dataType.getSelectedItem();
//    str[2]=jTF_width.getText();
//    str[3]=jTF_precision.getText();
//    str[4]=(String)jComboBox_NULL.getSelectedItem();
//    ((DefaultTableModel)jTable1.getModel()).addRow((Object[])str);
    }
}
//jTF_columnName.setText("");
//jTF_width.setText("");
//jTF_precision.setText("0");
}//GEN-LAST:event_jButton_AddColumnActionPerformed
private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
// TODO add your handling code here:
jTF_columnName.setText(null);
jTF_width.setText(null);
jComboBox_dataType.setSelectedIndex(0);
jComboBox_NULL.setSelectedIndex(0);
}//GEN-LAST:event_jButton_ClearActionPerformed
private void windowClosingTC(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingTC
 // TODO add your handling code here:
 int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to QUIT?","Message",JOptionPane.YES_NO_OPTION);
 if(confirm==0)
 {
        new MenuWindowFrame().setVisible(true);
        dispose();
        return;
 }
 else
        return;
}//GEN-LAST:event_windowClosingTC
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    int rowSelected[]=jTable1.getSelectedRows();
    if(rowSelected.length==0)
    {
        JOptionPane.showMessageDialog(null,"Please select atleast a single row to delete");
    }
    else
    {
        int confirm=JOptionPane.showConfirmDialog(null,"Are you sure to delete the column?","Message",JOptionPane.YES_NO_OPTION);
        if(confirm==0)
         {
            
        
            for(int i=0;i<rowSelected.length;i++)
               {
                   ((DefaultTableModel)jTable1.getModel()).removeRow(rowSelected[i]);
               }
         } 
    }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_dataTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_dataTypeItemStateChanged
        // TODO add your handling code here:
        if(jComboBox_dataType.getSelectedItem().equals("date"))
        {
            jTF_precision.setEditable(false);
            jTF_width.setEditable(false);
        }
        if(jComboBox_dataType.getSelectedItem().equals("varchar"))
        {
            jTF_width.setEditable(true);
            jTF_precision.setEditable(false);
        }
        if(jComboBox_dataType.getSelectedItem().equals("number"))
        {
            jTF_width.setEditable(true);
            jTF_precision.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_dataTypeItemStateChanged

    private void jComboBox_dataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_dataTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_dataTypeActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
public boolean isCellEditable(int row, int column) { 
return false; 
}
            @Override
            public void run() {
                new TableCreationFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_AddColumn;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_CreateTable;
    private javax.swing.JComboBox jComboBox_NULL;
    private javax.swing.JComboBox jComboBox_dataType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_TabelName;
    private javax.swing.JTextField jTF_columnName;
    private javax.swing.JTextField jTF_precision;
    private javax.swing.JTextField jTF_width;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
